spring.application.name=crm-vigenere

# Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/vigenere_db?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Escola21
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ESSENCIAL: rodar o data.sql depois que o Hibernate criar as tabelas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always